Winem st2resultstracker and ewc removal
StackStorm/st2-dockerfiles pull request #40
Opened 2020-11-05 10:15 UTC by winem

This PR removes the st2resultstracker container and EWC/Enterprise is no longer mentioned on the welcome banner. 

I hope it's ok to address both issues due to the small changes in a single PR.

close #39 
close #32

2020-11-05 11:42 UTC, armab commented on base/files/.welcome.sh
>  printf " * Forum: https://forum.stackstorm.com/\n"
Enterprise string below kept extra new line separators. Let's use them.
```suggestion
printf " * Forum: https://forum.stackstorm.com/\n\n"
```

2020-11-05 11:57 UTC, armab requested changes
Thanks for PR!
Yes, in every situation having 2 logically separated changes is ideal to solve in different PR, but OK for this time.

Before we remove st2resultstracker from the images, looks like it's used in https://github.com/StackStorm/st2-docker/blob/master/docker-compose.yml#L150. Worth removing those first.

2020-11-05 19:55 UTC, winem commented
Oh, of course! That's why I feel all day like I missed something.

2020-11-06 13:46 UTC, armab approved these changes
:+1:

2020-11-06 13:47 UTC, merged

2020-11-06 13:47 UTC, armab commented
Merged, thanks @winem!
cc @arms11